"""Deterministically resize the supplied icon; never modify the supplied logos.

Requires Pillow. Run from any directory: python scripts/generate-branding.py
Use --check to verify generated bytes and head links without writing files.
"""

import argparse
import hashlib
import io
from pathlib import Path
import re

from PIL import Image


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    directory = root / "public" / "branding"
    source_path = directory / "devcare-icon.png"
    revision = hashlib.sha256(source_path.read_bytes()).hexdigest()[:8]
    source = Image.open(source_path).convert("RGBA")
    if source.width != source.height:
        raise ValueError("The supplied compact icon must be square; no stretching is allowed.")

    generated = {}
    for size, prefix in [(16, "favicon-16"), (32, "favicon-32"), (180, "apple-touch-icon")]:
        output = io.BytesIO()
        source.resize((size, size), Image.Resampling.LANCZOS).save(
            output, format="PNG", optimize=False, compress_level=9
        )
        generated[f"devcare-{prefix}-{revision}.png"] = output.getvalue()

    sizes = [16, 32, 48, 64, 128, 256]
    frames = [source.resize((size, size), Image.Resampling.LANCZOS) for size in sizes]
    output = io.BytesIO()
    frames[-1].save(
        output,
        format="ICO",
        sizes=[(size, size) for size in sizes],
        append_images=frames[:-1],
        bitmap_format="png",
    )
    generated[f"devcare-favicon-{revision}.ico"] = output.getvalue()
    links = f'''    <!-- DevCare icons -->
    <link rel="icon" href="/branding/devcare-favicon-{revision}.ico" sizes="16x16 32x32 48x48 64x64 128x128 256x256" />
    <link rel="icon" type="image/png" sizes="16x16" href="/branding/devcare-favicon-16-{revision}.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="/branding/devcare-favicon-32-{revision}.png" />
    <link rel="apple-touch-icon" sizes="180x180" href="/branding/devcare-apple-touch-icon-{revision}.png" />
    <!-- /DevCare icons -->'''
    index_path = root / "index.html"
    html = index_path.read_text(encoding="utf-8")
    updated, count = re.subn(
        r"    <!-- DevCare icons -->[\s\S]*?    <!-- /DevCare icons -->", links, html
    )
    if count != 1:
        raise ValueError("Expected one DevCare icon block in index.html.")
    if args.check:
        for name, data in generated.items():
            if not (directory / name).exists() or (directory / name).read_bytes() != data:
                raise ValueError(f"Regenerate outdated or missing favicon: {name}")
        if html != updated:
            raise ValueError("Regenerate outdated favicon links in index.html.")
        print("Deterministic favicon bytes and document links verified.")
    else:
        for name, data in generated.items():
            (directory / name).write_bytes(data)
        index_path.write_text(updated, encoding="utf-8", newline="\n")
        print("Generated " + ", ".join(generated))


if __name__ == "__main__":
    main()
